use crate::types::Timestamp;
use anchor_lang::prelude::*;

/// Account used to store a guardian set. The keys encoded in this account are Ethereum pubkeys.
/// Its expiration time is determined at the time a guardian set is updated to a new set, where the
/// current network clock time is used with
/// [guardian_set_ttl](crate::state::Config::guardian_set_ttl).
///
/// NOTE: The account schema is the same as legacy guardian sets, but this account now has a
/// discriminator generated by Anchor's [account] macro. When the Core Bridge program performs a
/// guardian set update with this implementation, guardian sets will now have this Anchor-generated
/// discriminator.
#[account]
pub struct GuardianSet {
    /// Index representing an incrementing version number for this guardian set.
    pub index: u32,

    /// Ethereum-style public keys.
    pub keys: Vec<[u8; 20]>,

    /// Timestamp representing the time this guardian became active.
    pub creation_time: Timestamp,

    /// Expiration time when VAAs issued by this set are no longer valid.
    pub expiration_time: Timestamp,
}

impl GuardianSet {
    pub const SEED_PREFIX: &'static [u8] = b"GuardianSet";

    pub(crate) fn compute_size(num_guardians: usize) -> usize {
        8 // discriminator
        + 4 // index
        + 4 + num_guardians * 20 // keys
        + Timestamp::INIT_SPACE // creation_time
        + Timestamp::INIT_SPACE // expiration_time
    }
}
