use crate::types::MessageHash;
use anchor_lang::prelude::*;

/// Account used to store information about a guardian set used to sign a VAA. There is only one
/// signature set for each verified VAA (associated with a
/// [PostedVaaV1](crate::legacy::state::PostedVaaV1) account). This account is created using the
/// verify signatures legacy instruction.
///
/// NOTE: The account schema is the same as legacy signature sets, but this account now has a
/// discriminator generated by Anchor's [account] macro. When the Core Bridge program upgrades to
/// this implementation from the old one, integrators in the middle of verifying signatures will
/// have to use a new keypair for this account and try again.
#[account]
pub struct SignatureSet {
    /// Signatures of validators
    pub sig_verify_successes: Vec<bool>,

    /// Hash of the VAA message body.
    pub message_hash: MessageHash,

    /// Index of the guardian set
    pub guardian_set_index: u32,
}

impl SignatureSet {
    pub(crate) fn compute_size(num_signatures: usize) -> usize {
        8 // discriminator
        + 4 // Vec::len
        + num_signatures // signatures
        + MessageHash::INIT_SPACE // hash
        + 4 // guardian_set_index
    }

    pub fn is_initialized(&self) -> bool {
        self.sig_verify_successes.iter().any(|&value| value)
    }

    pub fn num_verified(&self) -> usize {
        self.sig_verify_successes
            .iter()
            .filter(|&&signed| signed)
            .count()
    }
}
