apiVersion: v1
kind: Service
metadata:
  labels:
    app: ibc-relayer
  name: ibc-relayer
spec:
  ports:
    - name: rest
      port: 3000
      protocol: TCP
    - name: telemetry
      port: 3001
      protocol: TCP
  selector:
    app: ibc-relayer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ibc-relayer
  name: ibc-relayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibc-relayer
  template:
    metadata:
      labels:
        app: ibc-relayer
    spec:
      containers:
        - name: ibc-relayer
          image: ibc-relayer-image
          command:
            - /bin/bash
            - -c
            - "/app/hermes-startup.sh"
          ports:
            - containerPort: 3000
              name: rest
              protocol: TCP
            - containerPort: 3001
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            periodSeconds: 1
      restartPolicy: Always
  serviceName: ibc-relayer
